<#
.SYNOPSIS
Read .mad/scratch/skill-timing.jsonl and the per-skill expected-duration
expectations from memory/feedback_skill_speed_expectations.md; emit a
markdown report that flags slow runs as candidates for workflow improvement.

.DESCRIPTION
Workflow-improvement signal layer (NOT enforcement). Different from
Track-SkillMetrics.ps1 in that:
  - Reads the user's expected-duration declarations from the memory rule
  - Computes (actual / expected) ratio per skill (last 10 runs)
  - Flags ratio > 1.5 as "candidate for workflow investigation"
  - Outputs an actionable markdown report at .mad/reports/

This is what a continuous-improvement loop reads to decide which skill body
needs the next round of pathology hunting.

Per workflow improvement plan fix #8: NOT a hook, NOT an abort mechanism. Just
visibility for orchestrator-level decisions about where to invest workflow
improvement effort next.

.PARAMETER OutputPath
Optional. Override the default report path
(.mad/reports/skill-workflow-audit-<date>.md).

.PARAMETER WindowSize
Number of most-recent runs per skill to include in the median/p90 computation.
Default: 10.

.PARAMETER FlagRatio
Ratio of (actual / expected) above which a skill is flagged for investigation.
Default: 1.5.

.EXAMPLE
pwsh -NoProfile -File .claude/scripts/Audit-SkillWorkflow.ps1

.EXAMPLE
pwsh -NoProfile -File .claude/scripts/Audit-SkillWorkflow.ps1 -WindowSize 20 -FlagRatio 2.0

.NOTES
Exit codes:
  0 = report generated, no skills flagged
  2 = report generated, at least one skill flagged for investigation
  3 = setup error (skill-timing.jsonl missing, or memory rule unparseable)
#>

param(
  [string]$OutputPath = "",
  [int]$WindowSize    = 10,
  [double]$FlagRatio  = 1.5
)

$ErrorActionPreference = "Stop"

$TimingPath = ".mad/scratch/skill-timing.jsonl"
if (-not (Test-Path $TimingPath)) {
  Write-Error "skill-timing.jsonl not found at $TimingPath - have any skills been invoked?"
  exit 3
}

# ---- Load expected durations from memory rule (best-effort parse) ----
$MemoryRule = Join-Path $env:USERPROFILE ".claude\projects\C--Users-tonym-Repos-MAD---Clean\memory\feedback_skill_speed_expectations.md"
$expected = @{}
if (Test-Path $MemoryRule) {
  $lines = Get-Content -Path $MemoryRule
  foreach ($line in $lines) {
    # Match lines like:  - /mad-spec:    5-15 min (target ~10)
    if ($line -match "^\s*-\s+/([a-z][a-z0-9-]*)\s*:\s*(\d+)-(\d+)\s+min(?:\s+\(target\s+~(\d+)\))?") {
      $skill = $matches[1]
      $low   = [int]$matches[2]
      $high  = [int]$matches[3]
      $target = if ($matches[4]) { [int]$matches[4] } else { [int](($low + $high) / 2) }
      $expected[$skill] = @{
        low_min       = $low
        high_min      = $high
        target_min    = $target
      }
    }
  }
}
if ($expected.Count -eq 0) {
  Write-Warning "No expected-duration entries parsed from $MemoryRule - report will only show actual durations without ratio judgement."
}

# ---- Load timing entries ----
$entries = @()
$lineNum = 0
foreach ($raw in (Get-Content -Path $TimingPath)) {
  $lineNum++
  $trimmed = $raw.Trim()
  if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }
  try {
    $entry = $trimmed | ConvertFrom-Json
    $entries += $entry
  } catch {
    Write-Warning "Skipping malformed line ${lineNum}: $($_.Exception.Message)"
  }
}

if ($entries.Count -eq 0) {
  Write-Error "No valid timing entries in $TimingPath"
  exit 3
}

# ---- Per-skill aggregation ----
$bySkill = $entries | Group-Object -Property skill

$report = New-Object System.Text.StringBuilder
$today = (Get-Date).ToString("yyyy-MM-dd")
$null = $report.AppendLine("# Skill workflow audit ($today)")
$null = $report.AppendLine()
$null = $report.AppendLine("Source: ``$TimingPath``")
$null = $report.AppendLine("Window: most-recent $WindowSize runs per skill")
$null = $report.AppendLine("Flag threshold: actual/expected ratio > $FlagRatio")
$null = $report.AppendLine()
$null = $report.AppendLine("Generated by ``.claude/scripts/Audit-SkillWorkflow.ps1``. NOT enforcement; signals where to invest workflow improvement effort.")
$null = $report.AppendLine()
$null = $report.AppendLine("## Summary")
$null = $report.AppendLine()
$null = $report.AppendLine("| Skill | Runs (window) | Median min | p90 min | Expected target min | Ratio (median/target) | Status |")
$null = $report.AppendLine("|---|---:|---:|---:|---:|---:|---|")

$flagged = @()
$details = New-Object System.Text.StringBuilder

foreach ($g in ($bySkill | Sort-Object -Property Name)) {
  $skill   = $g.Name
  $runs    = @($g.Group | Sort-Object -Property completed_at_ms -Descending | Select-Object -First $WindowSize)
  $durations = @($runs | ForEach-Object { [double]$_.duration_min })
  if ($durations.Count -eq 0) { continue }

  $sorted = $durations | Sort-Object
  $medianIdx = [Math]::Floor($sorted.Count / 2)
  $median = $sorted[$medianIdx]
  $p90Idx = [Math]::Min($sorted.Count - 1, [Math]::Floor($sorted.Count * 0.9))
  $p90 = $sorted[$p90Idx]

  $expEntry = $expected[$skill]
  if ($expEntry) {
    $target = $expEntry.target_min
    $ratio = [Math]::Round($median / $target, 2)
    $status = if ($ratio -gt $FlagRatio) {
      $flagged += $skill
      "FLAG (workflow investigation)"
    } else {
      "OK"
    }
  } else {
    $target = "(not declared)"
    $ratio  = "n/a"
    $status = "no expectation declared"
  }

  $null = $report.AppendLine("| /$skill | $($runs.Count) | $median | $p90 | $target | $ratio | $status |")

  # Per-skill detail section
  $null = $details.AppendLine("### /$skill")
  $null = $details.AppendLine()
  $null = $details.AppendLine("Last $($runs.Count) runs (most-recent first):")
  $null = $details.AppendLine()
  $null = $details.AppendLine("| Completed | Duration min | Notes |")
  $null = $details.AppendLine("|---|---:|---|")
  foreach ($r in $runs) {
    $iso = if ($r.completed_at_iso) { $r.completed_at_iso } else { "(unknown)" }
    $dur = $r.duration_min
    $notes = if ($r.notes) { $r.notes } else { "" }
    # Trim notes to keep table compact
    if ($notes.Length -gt 80) { $notes = $notes.Substring(0, 77) + "..." }
    $null = $details.AppendLine("| $iso | $dur | $notes |")
  }
  $null = $details.AppendLine()
  if ($expEntry) {
    $null = $details.AppendLine("Expected band: $($expEntry.low_min)-$($expEntry.high_min) min, target ~$($expEntry.target_min) min.")
    $null = $details.AppendLine()
  }
}

$null = $report.AppendLine()
$null = $report.AppendLine("## Per-skill detail")
$null = $report.AppendLine()
$null = $report.Append($details.ToString())

if ($flagged.Count -gt 0) {
  $null = $report.AppendLine("## Flagged for workflow investigation")
  $null = $report.AppendLine()
  foreach ($s in $flagged) {
    $null = $report.AppendLine("- /$s - median exceeds $FlagRatio x expected target. Investigate per `.mad/reports/phase3-time-analysis.md` (4 speed pathologies) + ``CLAUDE.md`` § Speed pathologies.")
  }
  $null = $report.AppendLine()
}

# Resolve output path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $ReportsDir = ".mad/reports"
  if (-not (Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir -Force | Out-Null
  }
  $OutputPath = Join-Path $ReportsDir "skill-workflow-audit-$today.md"
}

Set-Content -Path $OutputPath -Value $report.ToString() -Encoding UTF8

# Stdout summary
"Workflow audit written to: $OutputPath"
"Skills audited: $($bySkill.Count)"
"Flagged: $($flagged.Count)"
foreach ($s in $flagged) { "  - /$s" }

if ($flagged.Count -gt 0) {
  exit 2
}
exit 0
